### ISSUE TITLE
[ React Native ] "Your browser does not have secure random generator. If you don’t need unpredictable IDs, you can use nanoid/non-secure."

### ISSUE THREAD

**Issue by naomiHauret** [sergeysova/redux-symbiote#27]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/sergeysova/redux-symbiote/issues/27)

Hi ! First of all, thanks for all the work you did on redux-symbiote. It's a wonderful lib, writing redux-related code has never been so easy.
I'm developing 2 apps in React Native with Expo, and of course, redux-symbiote.
I upgraded `redux-symbiote` version from v`3.0.2` to v`3.1.0` and had this error since : 

```
Your browser does not have secure random generator. If you don’t need unpredictable IDs, you can use nanoid/non-secure.
```
I tried replacing `const nanoid = require("nanoid")` with `const nanoid = require("nanoid/non-secure")` in `src/index.js` but it didn't do the trick.

My workaround was to rollback to v`3.0.2` to get both my apps working again.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/5620073?v=4' alt='sergeysova' width=24 height=24> sergeysova](https://issuehunt.io/u/sergeysova) ($5.00)

### Submitted pull Requests
- [#34 Close #27. Nanoid/non-secure for old ie](https://issuehunt.io/r/sergeysova/redux-symbiote/pull/34)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sergeysova/redux-symbiote/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sergeysova** [comment]
@naomiHauret thanks

**Comment by sergeysova** [comment]
I don't have react-native project, but you can help us with debug that file:

https://github.com/sergeysova/redux-symbiote/blob/master/src/nanoid.js

**Comment by weyheyhey** [comment]
[https://github.com/sergeysova/redux-symbiote/blob/master/src/nanoid.js](url) works fine.

The problem is that in NPM not loaded version 3.2 (which contains this fix)

**Comment by sergeysova** [comment]
https://yarnpkg.com/en/package/redux-symbiote
https://npmjs.com/package/redux-symbiote

Version is released

**Comment by sergeysova** [comment]
@weyheyhey Please, check is problem solved

**Comment by weyheyhey** [comment]
@sergeysova Problem solved. Thank you)

**Comment by yyynnn** [comment]
Still it is also breaks in ie10 💩

**Comment by sergeysova** [comment]
@yyynnn redux-symbiote is not tested in ie10.
What error you have? Maybe create a new issue?

**Comment by kldkv** [comment]
I checked with browserstack. IE10, IE9 works.

```javascript
import { createStore } from 'redux'
import { createSymbiote } from "redux-symbiote";

const initialState = 0;

const symbiotes = {
  INCREMENT: state => state + 1,
  DECREMENT: state => state - 1
};

const { actions, reducer } = createSymbiote(
  initialState,
  symbiotes,
  "accounts/loading"
);

const store = createStore(reducer);

console.log(`Should be 0: ${store.getState()}`)
store.dispatch(actions.INCREMENT())
store.dispatch(actions.INCREMENT())
store.dispatch(actions.INCREMENT())
store.dispatch(actions.DECREMENT())
console.log(`Should be 2: ${store.getState()}`)

console.log(store, actions)
```
![Скриншот 2019-10-30 01 45 18](https://user-images.githubusercontent.com/6834243/67815346-bd18f780-fab7-11e9-8869-313bb051dfc3.png)
![Скриншот 2019-10-30 01 46 48](https://user-images.githubusercontent.com/6834243/67815348-bf7b5180-fab7-11e9-9274-78b8c3b3d160.png)

**Comment by sergeysova** [comment]
@kldkv Thank you!

**Comment by sergeysova** [comment]
@kldkv @naomiHauret

https://github.com/sergeysova/redux-symbiote/releases/tag/v3.4.0

Released
