### ISSUE TITLE
Types: derive actions type from the symbiotes type

### ISSUE THREAD

**Issue by Finesse** [sergeysova/redux-symbiote#28]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sergeysova/redux-symbiote/issues/28)

Current TypeScript implementation is not convenient because I have to describe the actions 2 times: the type and the implementation. Moreover, the `createSymbiote` type doesn't fully check that the actions type and implementation match.

```ts
// 1st actions description
interface Actions {
  foo(): Action;
  bar(arg: string): Action
}

// 2nd actions description
const symbiotes = {
  foo(state: State) {
    return {...state, value: 'foo'};
  },
  bar(state: State, value: number) { // The argument type mismatch is not checked
    return {...state, value: `bar ${value}`};
  }
};

const {actions, reducer} = createSymbiote<State, Actions>({value: 'Hi'}, symbiotes);
```

The single source of truth principle is broken.

I've made a draft of typing for `createSymbiote` that solves the problem. The function type derives the returned actions type from the input symbiotes type automagically:

```ts
export interface NamespaceOptions<State> {
  namespace?: string
  defaultReducer?: (prevState: State, action: Action) => State
  separator?: string
}

export type Symbiote<State> = (state: State, ...payload: any[]) => State

export type Reducer<State> = (state: State, action: Action) => State

export type Actions<Symbiotes> = {
  [Key in keyof Symbiotes]: Symbiotes[Key] extends Function
    ? ActionCreator<Symbiotes[Key]>
    : Actions<Symbiotes[Key]>
}

export interface Action<Payload = any> {
  type: string
  payload?: Payload
}

// Inspired by the built-in Parameters type
type ParametersFromSecond<T> = T extends (_: any, ...args: infer P) => any ? P : never;

type ActionCreator<Symbiote> = (...args: ParametersFromSecond<Symbiote>) => Action;

export function createSymbiote<State, Symbiotes>(
  initialState: State,
  actionsConfig: Symbiotes,
  namespaceOptions?: string | NamespaceOptions<State>,
): {
  actions: Actions<Symbiotes>
  reducer: Reducer<State>
}
```

The example can be converted with these types:

```ts
// Only 1 actions description
const symbiotes = {
  foo(state: State) {
    return {...state, value: 'foo'};
  },
  bar(state: State, value: number) {
    return {...state, value: `bar ${value}`};
  }
};

const {actions, reducer} = createSymbiote({value: 'Hi'}, symbiotes);

actions.bar('cocktail'); // TS error, a number is expected
```

I can make a PR if you agree. It'll be a breaking change for the typing.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/5620073?v=4' alt='sergeysova' width=24 height=24> sergeysova](https://issuehunt.io/u/sergeysova) ($5.00)
### Submitted pull Requests
- [#32 Types: derive actions type from the symbiotes type](https://issuehunt.io/r/sergeysova/redux-symbiote/pull/32)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sergeysova/redux-symbiote/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Finesse** [comment]
@sergeysova What can I do to help?

**Comment by sergeysova** [comment]
@Finesse You can fund the issue. https://issuehunt.io/r/sergeysova/redux-symbiote/issues/28

**Comment by Finesse** [comment]
@sergeysova What about me to write the code?

**Comment by sergeysova** [comment]
@Finesse PR Welcome!

**Comment by Finesse** [comment]
Is the types backward compatibility required? I can make a simple solution like in my draft that changes the types API. Or I can try to make backward compatible types, but I think it may be impossible.

**Comment by sergeysova** [comment]
You can implement types without backward compatibility
