### ISSUE TITLE
Fix url in doc

### ISSUE THREAD

**Issue by RusTorg** [sergeysova/redux-symbiote#31]
https://github.com/sergeysova/redux-symbiote/blob/master/README.md

from

`<img src="https://raw.githubusercontent.com/RusTorg/redux-symbiote/master/assets/logo.svg?sanitize=true" width="80" />`

to 

`<img src="https://raw.githubusercontent.com/sergeysova/redux-symbiote/master/assets/logo.svg?sanitize=true" width="80" />`

**Comment by sergeysova** [comment]
Thank you!
